package model.pojo;
// Generated 23-Mar-2017 11:45:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BuyerRenter generated by hbm2java
 */
public class BuyerRenter  implements java.io.Serializable {


     private int buyerRenterId;
     private String name;
     private String password;
     private String gender;
     private String address;
     private String telephone;
     private String email;
     private int age;
     private Date signupDate;
     private String image;
     private String buyerRenterUname;
     private Set offers = new HashSet(0);

    public BuyerRenter() {
    }

	
    public BuyerRenter(int buyerRenterID) {
        this.buyerRenterId=buyerRenterID;
    }
    public BuyerRenter(String name, String password, String gender, String address, String telephone, String email, int age,Date signupDate, String image, String buyerRenterUname) {
       //this.buyerRenterId=buyerRenterID;
       this.name = name;
       this.password = password;
       this.gender = gender;
       this.address = address;
       this.telephone = telephone;
       this.email = email;
       this.age = age;
       this.signupDate = signupDate;
       this.image = image;
       this.buyerRenterUname = buyerRenterUname;
//       this.offers = offers;
    }
    
    
    
    
    
    
    

//    public int getBuyerRenterId() {
//        return this.buyerRenterId;
//    }
//    
//    
//    public void setBuyerRenterId(int buyerRenterId) {
//        this.buyerRenterId = buyerRenterId;
//    }
//    public String getName() {
//        return this.name;
//    }
//    
//    public void setName(String name) {
//        this.name = name;
//    }
//    public String getPassword() {
//        return this.password;
//    }
//    
//    public void setPassword(String password) {
//        this.password = password;
//    }
//    public String getGender() {
//        return this.gender;
//    }
//    
//    public void setGender(String gender) {
//        this.gender = gender;
//    }
//    public String getAddress() {
//        return this.address;
//    }
//    
//    public void setAddress(String address) {
//        this.address = address;
//    }
//    public String getTelephone() {
//        return this.telephone;
//    }
//    
//    public void setTelephone(String telephone) {
//        this.telephone = telephone;
//    }
//    public String getEmail() {
//        return this.email;
//    }
//    
//    public void setEmail(String email) {
//        this.email = email;
//    }
//    public int getAge() {
//        return this.age;
//    }
//    
//    public void setAge(int age) {
//        this.age = age;
//    }
//    public Date getSignupDate() {
//        return this.signupDate;
//    }
//    
//    public void setSignupDate(Date signupDate) {
//        this.signupDate = signupDate;
//    }
//    public String getImage() {
//        return this.image;
//    }
//    
//    public void setImage(String image) {
//        this.image = image;
//    }
//    public String getBuyerRenterUname() {
//        return this.buyerRenterUname;
//    }
//    
//    public void setBuyerRenterUname(String buyerRenterUname) {
//        this.buyerRenterUname = buyerRenterUname;
//    }
//    public Set getOffers() {
//        return this.offers;
//    }
//    
//    public void setOffers(Set offers) {
//        this.offers = offers;
//    }
//

    public int getBuyerRenterId() {
        return buyerRenterId;
    }

    public void setBuyerRenterId(int buyerRenterId) {
        this.buyerRenterId = buyerRenterId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public Date getSignupDate() {
        return signupDate;
    }

    public void setSignupDate(Date signupDate) {
        this.signupDate = signupDate;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getBuyerRenterUname() {
        return buyerRenterUname;
    }

    public void setBuyerRenterUname(String buyerRenterUname) {
        this.buyerRenterUname = buyerRenterUname;
    }

    public Set getOffers() {
        return offers;
    }

    public void setOffers(Set offers) {
        this.offers = offers;
    }



}


