package model.pojo;
// Generated 21-Mar-2017 20:47:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Offer generated by hbm2java
 */
public class Offer  implements java.io.Serializable {


     private Integer idoffer;
     private Integer buyerRenterID;
     private Integer propertyPostsID;
     private Date date;
     private double amount;
     private String comment;
     private int approval;
     private Date approvalDate;
     private String currency;

    public Offer() {
    }

	
    public Offer(Date date, double amount, int approval, String currency) {
        this.date = date;
        this.amount = amount;
        this.approval = approval;
        this.currency = currency;
    }
    public Offer(int buyerRenterID, int propertyPostsID, Date date, double amount, String comment, int approval, Date approvalDate, String currency) {
       this.buyerRenterID = buyerRenterID;
       this.propertyPostsID = propertyPostsID;
       this.date = date;
       this.amount = amount;
       this.comment = comment;
       this.approval = approval;
       this.approvalDate = approvalDate;
       this.currency = currency;
    }
   
    public Integer getIdoffer() {
        return this.idoffer;
    }
    
    public void setIdoffer(Integer idoffer) {
        this.idoffer = idoffer;
    }
    public Integer getBuyerRenterID() {
        return this.buyerRenterID;
    }
    
    public void setBuyerRenterID(int buyerRenterID) {
        this.buyerRenterID = buyerRenterID;
    }
    public Integer getPropertyPostsID() {
        return this.propertyPostsID;
    }
    
    public void setPropertyPostsID(int propertyPostsID) {
        this.propertyPostsID = propertyPostsID;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public int getApproval() {
        return this.approval;
    }
    
    public void setApproval(int approval) {
        this.approval = approval;
    }
    public Date getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }




}


