package model.pojo;
// Generated 21-Mar-2017 20:47:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PropertyOwner generated by hbm2java
 */
public class PropertyOwner  implements java.io.Serializable {


     private Integer propertyOwnerId;
     private String name;
     private String password;
     private String gender;
     private String address;
     private String telephone;
     private String email;
     private Date dob;
     private Date signupDate;
     private String image;
     private String propertyOwnerUname;
     private Set propertyPostses = new HashSet(0);

    public PropertyOwner() {
    }

	
    public PropertyOwner(String name, String password, String address, String telephone, String email, Date dob, Date signupDate, String propertyOwnerUname) {
        this.name = name;
        this.password = password;
        this.address = address;
        this.telephone = telephone;
        this.email = email;
        this.dob = dob;
        this.signupDate = signupDate;
        this.propertyOwnerUname = propertyOwnerUname;
    }
    public PropertyOwner(String name, String password, String gender, String address, String telephone, String email, Date dob, Date signupDate, String image, String propertyOwnerUname, Set propertyPostses) {
       this.name = name;
       this.password = password;
       this.gender = gender;
       this.address = address;
       this.telephone = telephone;
       this.email = email;
       this.dob = dob;
       this.signupDate = signupDate;
       this.image = image;
       this.propertyOwnerUname = propertyOwnerUname;
       this.propertyPostses = propertyPostses;
    }
   
    public Integer getPropertyOwnerId() {
        return this.propertyOwnerId;
    }
    
    public void setPropertyOwnerId(Integer propertyOwnerId) {
        this.propertyOwnerId = propertyOwnerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getSignupDate() {
        return this.signupDate;
    }
    
    public void setSignupDate(Date signupDate) {
        this.signupDate = signupDate;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getPropertyOwnerUname() {
        return this.propertyOwnerUname;
    }
    
    public void setPropertyOwnerUname(String propertyOwnerUname) {
        this.propertyOwnerUname = propertyOwnerUname;
    }
    public Set getPropertyPostses() {
        return this.propertyPostses;
    }
    
    public void setPropertyPostses(Set propertyPostses) {
        this.propertyPostses = propertyPostses;
    }




}


