package model.pojo;
// Generated 21-Mar-2017 20:47:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PropertyPosts generated by hbm2java
 */
public class PropertyPosts  implements java.io.Serializable {


     private int idpropertyPosts;
     private int estateAgent;
     private int propertyOwner;
     private String title;
     private String description;
     private String propertyType;
     private String address;
     private String postcode;
     private int bedroomCount;
     private int bathroomCount;
     private String furnishingStatus;
     private int garage;
     private int garden;
     private int parking;
     private double size;
     private String adType;
     private int price;
     private int postingStatus;
     private Date postDate;
     private String images;
     private Set feedbacks = new HashSet(0);
     private Set offers = new HashSet(0);

    public PropertyPosts() {
    }

	
    public PropertyPosts(String title, String description, String propertyType, String address, String postcode, int bedroomCount, int bathroomCount, String furnishingStatus, int garage, int garden, int parking, double size, String adType, int price, int postingStatus, Date postDate) {
        this.title = title;
        this.description = description;
        this.propertyType = propertyType;
        this.address = address;
        this.postcode = postcode;
        this.bedroomCount = bedroomCount;
        this.bathroomCount = bathroomCount;
        this.furnishingStatus = furnishingStatus;
        this.garage = garage;
        this.garden = garden;
        this.parking = parking;
        this.size = size;
        this.adType = adType;
        this.price = price;
        this.postingStatus = postingStatus;
        this.postDate = postDate;
    }
    public PropertyPosts(int estateAgent, int propertyOwner, String title, String description, String propertyType, String address, String postcode, int bedroomCount, int bathroomCount, String furnishingStatus, int garage, int garden, int parking, double size, String adType, int price, int postingStatus, Date postDate, String images, Set feedbacks, Set offers) {
       this.estateAgent = estateAgent;
       this.propertyOwner = propertyOwner;
       this.title = title;
       this.description = description;
       this.propertyType = propertyType;
       this.address = address;
       this.postcode = postcode;
       this.bedroomCount = bedroomCount;
       this.bathroomCount = bathroomCount;
       this.furnishingStatus = furnishingStatus;
       this.garage = garage;
       this.garden = garden;
       this.parking = parking;
       this.size = size;
       this.adType = adType;
       this.price = price;
       this.postingStatus = postingStatus;
       this.postDate = postDate;
       this.images = images;
       this.feedbacks = feedbacks;
       this.offers = offers;
    }
   
    public Integer getIdpropertyPosts() {
        return this.idpropertyPosts;
    }
    
    public void setIdpropertyPosts(int idpropertyPosts) {
        this.idpropertyPosts = idpropertyPosts;
    }
    public int getEstateAgent() {
        return this.estateAgent;
    }
    
    public void setEstateAgent(int estateAgent) {
        this.estateAgent = estateAgent;
    }
    public int getPropertyOwner() {
        return this.propertyOwner;
    }
    
    public void setPropertyOwner(int propertyOwner) {
        this.propertyOwner = propertyOwner;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPropertyType() {
        return this.propertyType;
    }
    
    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public int getBedroomCount() {
        return this.bedroomCount;
    }
    
    public void setBedroomCount(int bedroomCount) {
        this.bedroomCount = bedroomCount;
    }
    public int getBathroomCount() {
        return this.bathroomCount;
    }
    
    public void setBathroomCount(int bathroomCount) {
        this.bathroomCount = bathroomCount;
    }
    public String getFurnishingStatus() {
        return this.furnishingStatus;
    }
    
    public void setFurnishingStatus(String furnishingStatus) {
        this.furnishingStatus = furnishingStatus;
    }
    public int getGarage() {
        return this.garage;
    }
    
    public void setGarage(int garage) {
        this.garage = garage;
    }
    public int getGarden() {
        return this.garden;
    }
    
    public void setGarden(int garden) {
        this.garden = garden;
    }
    public int getParking() {
        return this.parking;
    }
    
    public void setParking(int parking) {
        this.parking = parking;
    }
    public double getSize() {
        return this.size;
    }
    
    public void setSize(double size) {
        this.size = size;
    }
    public String getAdType() {
        return this.adType;
    }
    
    public void setAdType(String adType) {
        this.adType = adType;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getPostingStatus() {
        return this.postingStatus;
    }
    
    public void setPostingStatus(int postingStatus) {
        this.postingStatus = postingStatus;
    }
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }
    public String getImages() {
        return this.images;
    }
    
    public void setImages(String images) {
        this.images = images;
    }
    public Set getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set feedbacks) {
        this.feedbacks = feedbacks;
    }
    public Set getOffers() {
        return this.offers;
    }
    
    public void setOffers(Set offers) {
        this.offers = offers;
    }




}


